

export type OrderHeader = {
    id: string | number;
    store_id: string | number;
    sale_channel_id: string | number;
    delivery_type_id: string | number;
    payment_method_id: string | number;
    payment_time_id: string | number;
    customer_id: string | number;
    loyalty_card_id: string | number;
    created_by: string | number;
    approved_by: string | number;
    managed_by: string | number;
    order_no: string;
    customer_notes: string;
    price_before_tax: decimal;
    total_tax_value: decimal;
    price_after_tax: decimal;
    price_before_discount: decimal;
    order_items_discount: decimal;
    order_discount: decimal;
    total_discount_value: decimal;
    price_after_discount: decimal;
    price_adjustment: decimal;
    price_adjustment_reason: string;
    price: decimal;
    latest_status: string;
    latest_status_update: string;
    is_submitted: boolean;
    submitted_time: string;
    is_approved: boolean;
    approved_time: string;
    is_canceled: boolean;
    canceled_time: string;
    cancel_reason: string;
    is_scheduled: boolean;
    scheduled_time: string;
    is_ready: boolean;
    ready_time: string;
    is_delivered: boolean;
    delivered_time: string;
    is_paid: boolean;
    payment_time: string;
    is_completed: boolean;
    completed_time: string;
    return_required: boolean;
    return_time: string;
    comments: string;
    
};

export type OrderHeaderForm = {
    store_id: string | number;
    sale_channel_id: string | number;
    delivery_type_id: string | number;
    payment_method_id: string | number;
    payment_time_id: string | number;
    customer_id: string | number;
    loyalty_card_id: string | number;
    created_by: string | number;
    approved_by: string | number;
    managed_by: string | number;
    order_no: string;
    customer_notes: string;
    price_before_tax: decimal;
    total_tax_value: decimal;
    price_after_tax: decimal;
    price_before_discount: decimal;
    order_items_discount: decimal;
    order_discount: decimal;
    total_discount_value: decimal;
    price_after_discount: decimal;
    price_adjustment: decimal;
    price_adjustment_reason: string;
    price: decimal;
    latest_status: string;
    latest_status_update: string;
    is_submitted: boolean;
    submitted_time: string;
    is_approved: boolean;
    approved_time: string;
    is_canceled: boolean;
    canceled_time: string;
    cancel_reason: string;
    is_scheduled: boolean;
    scheduled_time: string;
    is_ready: boolean;
    ready_time: string;
    is_delivered: boolean;
    delivered_time: string;
    is_paid: boolean;
    payment_time: string;
    is_completed: boolean;
    completed_time: string;
    return_required: boolean;
    return_time: string;
    comments: string;
};
