<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'customers';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'city_id',
        'created_at_store_id',
        'created_by',
        'code',
        'phone',
        'first_name',
        'last_name',
        'is_company',
        'company_name',
        'tax_number',
        'is_tax_exempted',
        'billing_address',
        'postal_code',
        'is_registered_online',
        'email',
        'username',
        'password',
        'credit',
        'last_login_time',
        'is_active',
        'comments',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'city_id' => 'integer',
        'created_at_store_id' => 'integer',
        'created_by' => 'integer',
        'is_company' => 'boolean',
        'is_tax_exempted' => 'boolean',
        'is_registered_online' => 'boolean',
        'credit' => 'decimal',
        'last_login_time' => 'datetime',
        'is_active' => 'boolean',
    ];
    }
}
