<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DiscountType extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'discount_types';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'loyalty_card_type_id',
        'name',
        'description',
        'is_percentage',
        'value',
        'coupon_code',
        'min_order_value',
        'min_item_quantity',
        'apply_to_all',
        'apply_to_next',
        'max_discount_value',
        'start_time',
        'end_time',
        'is_active',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'loyalty_card_type_id' => 'integer',
        'is_percentage' => 'boolean',
        'value' => 'decimal',
        'min_order_value' => 'decimal',
        'apply_to_all' => 'boolean',
        'apply_to_next' => 'boolean',
        'max_discount_value' => 'decimal',
        'start_time' => 'datetime',
        'end_time' => 'datetime',
        'is_active' => 'boolean',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function loyaltyCardType(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(LoyaltyCardType::class);
    }

    public function discounts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Discount::class);
    }
}
