<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'documents';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'document_type_id',
        'sale_order_id',
        'purchase_id',
        'stock_return_id',
        'inventory_count_id',
        'loss_and_damage_id',
        'created_by',
        'number',
        'external_number',
        'description',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'document_type_id' => 'integer',
        'sale_order_id' => 'integer',
        'purchase_id' => 'integer',
        'stock_return_id' => 'integer',
        'inventory_count_id' => 'integer',
        'loss_and_damage_id' => 'integer',
        'created_by' => 'integer',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function documentType(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(DocumentType::class);
    }

    public function saleOrder(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(OrderHeader::class, 'sale_order_id');
    }

    public function purchase(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Purchase::class);
    }

    public function stockReturn(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(StockReturn::class);
    }

    public function inventoryCount(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(InventoryCount::class);
    }

    public function lossAndDamage(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(LossAndDamage::class);
    }

    public function createdBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\Brackets\CraftablePro\Models\CraftableProUser::class, 'created_by');
    }

    public function stockHistories(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(StockHistory::class);
    }
}
