<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'documents';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'document_type_id',
        'sale_order_id',
        'purchase_id',
        'stock_return_id',
        'inventory_count_id',
        'loss_and_damage_id',
        'created_by',
        'number',
        'external_number',
        'description',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'document_type_id' => 'integer',
        'sale_order_id' => 'integer',
        'purchase_id' => 'integer',
        'stock_return_id' => 'integer',
        'inventory_count_id' => 'integer',
        'loss_and_damage_id' => 'integer',
        'created_by' => 'integer',
    ];
    }
}
