<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use App\Models\Concerns\HasGeneratedCode;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use HasFactory;
    use HasGeneratedCode;

    /** @return array<string, callable> */
    protected function generatedCodes(): array
    {
        return ['invoice_no' => fn (self $invoice) => static::generateInvoiceNo($invoice->order_id)];
    }

    /**
     * INV-000005 — keyed to the order, so an invoice is traceable to its sale.
     * Falls back to a -2, -3 … suffix if an order ever carries a second invoice.
     */
    public static function generateInvoiceNo(int|string|null $orderId): string
    {
        $base = 'INV-' . str_pad((string) $orderId, 6, '0', STR_PAD_LEFT);

        if (! static::query()->where('invoice_no', $base)->exists()) {
            return $base;
        }

        $n = 2;
        while (static::query()->where('invoice_no', "{$base}-{$n}")->exists()) {
            $n++;
        }

        return "{$base}-{$n}";
    }

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'invoices';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'order_id',
        'invoice_no',
        'is_paid',
        'payment_time',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'order_id' => 'integer',
        'is_paid' => 'boolean',
        'payment_time' => 'datetime',
    ];
    }

    public function order(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(OrderHeader::class, 'order_id');
    }

    public function invoiceLines(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(InvoiceLine::class);
    }

    public function payments(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Payment::class);
    }
}
