<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use App\Models\Concerns\HasGeneratedCode;
use Brackets\CraftablePro\Media\AutoProcessMediaTrait;
use Brackets\CraftablePro\Media\HasMediaPreviewsTrait;
use Brackets\CraftablePro\Media\InteractsWithMedia;
use Brackets\CraftablePro\Media\ProcessMediaTrait;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;

class Item extends Model implements HasMedia
{
    use HasFactory;
    use HasGeneratedCode;

    /** @return array<string, callable> */
    protected function generatedCodes(): array
    {
        return ['sku_code' => fn () => static::sequentialCode('sku_code', 'SKU-', 6)];
    }
    use InteractsWithMedia;
    use ProcessMediaTrait;
    use AutoProcessMediaTrait;
    use HasMediaPreviewsTrait;

    /**
     * Expose media as form/display attributes.
     */
    protected $appends = ['images', 'images_url'];

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('images')
            ->acceptsMimeTypes(['image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/webp'])
            ->maxFileSize(5 * 1024 * 1024);
    }

    public function registerMediaConversions($media = null): void
    {
        $this->autoRegisterPreviews();
    }

    /**
     * Media collection for the form (array of uploaded files).
     */
    protected function images(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => $this->getThumbs200ForCollection('images'),
        );
    }

    /**
     * First image URL for grid/list thumbnails.
     */
    protected function imagesUrl(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => $this->getFirstMediaUrl('images', 'preview'),
        );
    }

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'items';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'item_category_id',
        'supplier_id',
        'measure_unit_id',
        'sku_code',
        'name',
        'image',
        'description',
        'is_service',
        'in_stock',
        'using_default_quantity',
        'default_quantity',
        'current_stock_quantity',
        'preferred_stock_quantity',
        'min_stock_quantity',
        'low_stock_warning',
        'low_stock_quantity',
        'is_active',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'item_category_id' => 'integer',
        'supplier_id' => 'integer',
        'measure_unit_id' => 'integer',
        'is_service' => 'boolean',
        'in_stock' => 'boolean',
        'using_default_quantity' => 'boolean',
        'low_stock_warning' => 'boolean',
        'is_active' => 'boolean',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function itemCategory(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(ItemCategory::class);
    }

    public function supplier(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Supplier::class);
    }

    public function measureUnit(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(MeasureUnit::class);
    }

    public function barCodes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(BarCode::class);
    }

    public function prices(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Price::class);
    }

    /**
     * The current sellable price — newest row that passes the active() window
     * (is_active + start/end time). Used by the POS / catalog.
     */
    public function activePrice(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(Price::class)->ofMany(
            ['id' => 'max'],
            fn ($query) => $query->active(),
        );
    }

    public function orderLines(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderLine::class);
    }

    public function supplierItemTaxTypes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(SupplierItemTaxType::class);
    }

    public function discounts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Discount::class);
    }

    public function itemTaxTypes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(ItemTaxType::class);
    }

    public function purchaseItems(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(PurchaseItem::class);
    }

    public function inventoryCountItems(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(InventoryCountItem::class);
    }

    public function lossAndDamageItems(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(LossAndDamageItem::class);
    }

    public function stockReturnItems(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(StockReturnItem::class);
    }

    public function stockHistories(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(StockHistory::class);
    }

    public function saleReturnItems(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(SaleReturnItem::class);
    }
}
