<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'items';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'item_category_id',
        'supplier_id',
        'measure_unit_id',
        'sku_code',
        'name',
        'description',
        'is_service',
        'in_stock',
        'using_default_quantity',
        'default_quantity',
        'current_stock_quantity',
        'preferred_stock_quantity',
        'min_stock_quantity',
        'low_stock_warning',
        'low_stock_quantity',
        'is_active',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'item_category_id' => 'integer',
        'supplier_id' => 'integer',
        'measure_unit_id' => 'integer',
        'is_service' => 'boolean',
        'in_stock' => 'boolean',
        'using_default_quantity' => 'boolean',
        'low_stock_warning' => 'boolean',
        'is_active' => 'boolean',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function itemCategory(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(ItemCategory::class);
    }

    public function supplier(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Supplier::class);
    }

    public function measureUnit(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(MeasureUnit::class);
    }

    public function barCodes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(BarCode::class);
    }

    public function prices(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Price::class);
    }

    public function orderLines(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderLine::class);
    }

    public function supplierItemTaxTypes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(SupplierItemTaxType::class);
    }

    public function discounts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Discount::class);
    }
}
