<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use App\Models\Concerns\HasGeneratedCode;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderLine extends Model
{
    use HasFactory;
    use HasGeneratedCode;

    /** @return array<string, callable> */
    protected function generatedCodes(): array
    {
        return ['line_no' => fn (self $line) => static::nextLineNo('order_id', $line->order_id)];
    }

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'order_lines';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'order_id',
        'item_id',
        'line_no',
        'description',
        'customer_notes',
        'quantity',
        'current_item_cost',
        'markup_percentage',
        'price_before_tax',
        'tax_value',
        'price_after_tax',
        'price_before_discount',
        'discount_value',
        'price_after_discount',
        'price_adjustment',
        'price_adjustment_reason',
        'price',
        'is_canceled',
        'canceled_time',
        'cancel_reason',
        'return_required',
        'return_quantity',
        'return_time',
        'customer_review',
        'customer_like',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'order_id' => 'integer',
        'item_id' => 'integer',
        'current_item_cost' => 'decimal:3',
        'price_before_tax' => 'decimal:3',
        'tax_value' => 'decimal:3',
        'price_after_tax' => 'decimal:3',
        'price_before_discount' => 'decimal:3',
        'discount_value' => 'decimal:3',
        'price_after_discount' => 'decimal:3',
        'price_adjustment' => 'decimal:3',
        'price' => 'decimal:3',
        'is_canceled' => 'boolean',
        'canceled_time' => 'datetime',
        'return_required' => 'boolean',
        'return_time' => 'datetime',
        'customer_like' => 'boolean',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function order(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(OrderHeader::class, 'order_id');
    }

    public function item(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Item::class);
    }

    public function orderLineDiscounts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderLineDiscount::class, 'order_line_id');
    }

    public function invoiceLines(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(InvoiceLine::class, 'order_line_id');
    }

    public function saleReturnItems(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(SaleReturnItem::class, 'order_line_id');
    }
}
