<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderHeader extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'order_headers';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'sale_channel_id',
        'delivery_type_id',
        'payment_method_id',
        'payment_time_id',
        'customer_id',
        'loyalty_card_id',
        'created_by',
        'approved_by',
        'managed_by',
        'order_no',
        'customer_notes',
        'price_before_tax',
        'total_tax_value',
        'price_after_tax',
        'price_before_discount',
        'order_items_discount',
        'order_discount',
        'total_discount_value',
        'price_after_discount',
        'price_adjustment',
        'price_adjustment_reason',
        'price',
        'latest_status',
        'latest_status_update',
        'is_submitted',
        'submitted_time',
        'is_approved',
        'approved_time',
        'is_canceled',
        'canceled_time',
        'cancel_reason',
        'is_scheduled',
        'scheduled_time',
        'is_ready',
        'ready_time',
        'is_delivered',
        'delivered_time',
        'is_paid',
        'payment_time',
        'is_completed',
        'completed_time',
        'return_required',
        'return_time',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'sale_channel_id' => 'integer',
        'delivery_type_id' => 'integer',
        'payment_method_id' => 'integer',
        'payment_time_id' => 'integer',
        'customer_id' => 'integer',
        'loyalty_card_id' => 'integer',
        'created_by' => 'integer',
        'approved_by' => 'integer',
        'managed_by' => 'integer',
        'price_before_tax' => 'decimal',
        'total_tax_value' => 'decimal',
        'price_after_tax' => 'decimal',
        'price_before_discount' => 'decimal',
        'order_items_discount' => 'decimal',
        'order_discount' => 'decimal',
        'total_discount_value' => 'decimal',
        'price_after_discount' => 'decimal',
        'price_adjustment' => 'decimal',
        'price' => 'decimal',
        'latest_status_update' => 'datetime',
        'is_submitted' => 'boolean',
        'submitted_time' => 'datetime',
        'is_approved' => 'boolean',
        'approved_time' => 'datetime',
        'is_canceled' => 'boolean',
        'canceled_time' => 'datetime',
        'is_scheduled' => 'boolean',
        'scheduled_time' => 'datetime',
        'is_ready' => 'boolean',
        'ready_time' => 'datetime',
        'is_delivered' => 'boolean',
        'delivered_time' => 'datetime',
        'is_paid' => 'boolean',
        'payment_time' => 'datetime',
        'is_completed' => 'boolean',
        'completed_time' => 'datetime',
        'return_required' => 'boolean',
        'return_time' => 'datetime',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function saleChannel(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(SaleChannel::class);
    }

    public function deliveryType(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(DeliveryType::class);
    }

    public function paymentMethod(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(PaymentMethod::class);
    }

    public function paymentTime(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(PaymentTime::class);
    }

    public function customer(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    public function loyaltyCard(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(LoyaltyCard::class);
    }

    public function createdBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\Brackets\CraftablePro\Models\CraftableProUser::class, 'created_by');
    }

    public function approvedBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\Brackets\CraftablePro\Models\CraftableProUser::class, 'approved_by');
    }

    public function managedBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\Brackets\CraftablePro\Models\CraftableProUser::class, 'managed_by');
    }

    public function orderLines(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderLine::class, 'order_id');
    }

    public function orderStatusHistories(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderStatusHistory::class, 'order_id');
    }
}
