<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderLine extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'order_lines';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'order_id',
        'item_id',
        'line_no',
        'description',
        'customer_notes',
        'quantity',
        'current_item_cost',
        'markup_percentage',
        'price_before_tax',
        'tax_value',
        'price_after_tax',
        'price_before_discount',
        'discount_value',
        'price_after_discount',
        'price_adjustment',
        'price_adjustment_reason',
        'price',
        'is_canceled',
        'canceled_time',
        'cancel_reason',
        'return_required',
        'return_quantity',
        'return_time',
        'customer_review',
        'customer_like',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'order_id' => 'integer',
        'item_id' => 'integer',
        'current_item_cost' => 'decimal',
        'price_before_tax' => 'decimal',
        'tax_value' => 'decimal',
        'price_after_tax' => 'decimal',
        'price_before_discount' => 'decimal',
        'discount_value' => 'decimal',
        'price_after_discount' => 'decimal',
        'price_adjustment' => 'decimal',
        'price' => 'decimal',
        'is_canceled' => 'boolean',
        'canceled_time' => 'datetime',
        'return_required' => 'boolean',
        'return_time' => 'datetime',
        'customer_like' => 'boolean',
    ];
    }
}
