<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PaymentTerm extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'payment_terms';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'sale_channel_id',
        'delivery_type_id',
        'payment_method_id',
        'payment_time_id',
        'is_allowed',
        'is_active',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'sale_channel_id' => 'integer',
        'delivery_type_id' => 'integer',
        'payment_method_id' => 'integer',
        'payment_time_id' => 'integer',
        'is_allowed' => 'boolean',
        'is_active' => 'boolean',
    ];
    }
}
