<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Price extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'prices';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'item_id',
        'store_id',
        'created_by',
        'description',
        'current_item_cost',
        'markup_percentage',
        'price_before_tax',
        'tax_value',
        'price_after_tax',
        'sale_price',
        'price_change_allowed',
        'start_time',
        'end_time',
        'is_active',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'item_id' => 'integer',
        'store_id' => 'integer',
        'created_by' => 'integer',
        'current_item_cost' => 'decimal',
        'price_before_tax' => 'decimal',
        'tax_value' => 'decimal',
        'price_after_tax' => 'decimal',
        'sale_price' => 'decimal',
        'price_change_allowed' => 'boolean',
        'start_time' => 'datetime',
        'end_time' => 'datetime',
        'is_active' => 'boolean',
    ];
    }
}
