<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Refund extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'refunds';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'sale_return_id',
        'payment_method_id',
        'refund_no',
        'amount',
        'cash_paid',
        'cash_change',
        'refund_time',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'sale_return_id' => 'integer',
        'payment_method_id' => 'integer',
        'amount' => 'decimal',
        'cash_paid' => 'decimal',
        'cash_change' => 'decimal',
        'refund_time' => 'datetime',
    ];
    }
}
