<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SaleReturn extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'sale_returns';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'order_id',
        'entry_stock_time',
        'is_refund_required',
        'refund_amount',
        'is_refunded',
        'refund_time',
        'description',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'order_id' => 'integer',
        'entry_stock_time' => 'datetime',
        'is_refund_required' => 'boolean',
        'refund_amount' => 'decimal',
        'is_refunded' => 'boolean',
        'refund_time' => 'datetime',
    ];
    }
}
