<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shipment extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'shipments';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'order_id',
        'shipment_city_id',
        'picked_up_by',
        'shipment_address',
        'gps_location',
        'postal_code',
        'shipment_notes',
        'picked_up_time',
        'shipped_time',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'order_id' => 'integer',
        'shipment_city_id' => 'integer',
        'picked_up_by' => 'integer',
        'picked_up_time' => 'datetime',
        'shipped_time' => 'datetime',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function order(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(OrderHeader::class, 'order_id');
    }

    public function shipmentCity(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(City::class, 'shipment_city_id');
    }

    public function pickedUpBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\Brackets\CraftablePro\Models\CraftableProUser::class, 'picked_up_by');
    }
}
