<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StockReturnItem extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'stock_return_items';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'stock_return_id',
        'item_id',
        'quantity',
        'supplier_price_before_tax',
        'supplier_tax_value',
        'supplier_price_after_tax',
        'supplier_discount_value',
        'return_amount',
        'description',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'stock_return_id' => 'integer',
        'item_id' => 'integer',
        'supplier_price_before_tax' => 'decimal:3',
        'supplier_tax_value' => 'decimal:3',
        'supplier_price_after_tax' => 'decimal:3',
        'supplier_discount_value' => 'decimal:3',
        'return_amount' => 'decimal:3',
    ];
    }

    public function stockReturn(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(StockReturn::class);
    }

    public function item(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Item::class);
    }
}
