<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use App\Models\Concerns\HasGeneratedCode;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    use HasFactory;
    use HasGeneratedCode;

    /** @return array<string, callable> */
    protected function generatedCodes(): array
    {
        return ['code' => fn () => static::sequentialCode('code', 'STR-', 2)];
    }

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'stores';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'city_id',
        'language_id',
        'currency_id',
        'code',
        'name',
        'is_active',
        'legal_entity_name',
        'tax_code',
        'address',
        'registration_number',
        'phone',
        'fax',
        'email',
        'logo',
        'bank_branch',
        'bank_code',
        'bank_account',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'city_id' => 'integer',
        'language_id' => 'integer',
        'currency_id' => 'integer',
        'is_active' => 'boolean',
    ];
    }

    public function city(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function language(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Language::class);
    }

    public function currency(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Currency::class);
    }

    public function taxTypes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(TaxType::class);
    }

    public function suppliers(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Supplier::class);
    }

    public function customers(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Customer::class, 'created_at_store_id');
    }

    public function items(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Item::class);
    }

    public function prices(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Price::class);
    }

    public function discountTypes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(DiscountType::class);
    }

    public function orderHeaders(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderHeader::class);
    }

    public function orderLines(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderLine::class);
    }

    public function holidays(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Holiday::class);
    }

    public function shipments(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Shipment::class);
    }

    public function purchases(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Purchase::class);
    }

    public function inventoryCounts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(InventoryCount::class);
    }

    public function lossAndDamages(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(LossAndDamage::class);
    }

    public function stockReturns(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(StockReturn::class);
    }

    public function documents(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Document::class);
    }

    public function stockHistories(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(StockHistory::class);
    }

    public function saleReturns(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(SaleReturn::class);
    }
}
