<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'stores';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'city_id',
        'language_id',
        'currency_id',
        'code',
        'name',
        'is_active',
        'legal_entity_name',
        'tax_code',
        'address',
        'registration_number',
        'phone',
        'fax',
        'email',
        'logo',
        'bank_branch',
        'bank_code',
        'bank_account',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'city_id' => 'integer',
        'language_id' => 'integer',
        'currency_id' => 'integer',
        'is_active' => 'boolean',
    ];
    }
}
