<?php

/** Auto-generated by Craftable PRO and Laravel Blueprint */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'suppliers';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'store_id',
        'city_id',
        'created_by',
        'code',
        'phone',
        'first_name',
        'last_name',
        'is_company',
        'company_name',
        'tax_number',
        'is_tax_exempted',
        'billing_address',
        'postal_code',
        'email',
        'is_active',
        'comments',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
        'id' => 'integer',
        'store_id' => 'integer',
        'city_id' => 'integer',
        'created_by' => 'integer',
        'is_company' => 'boolean',
        'is_tax_exempted' => 'boolean',
        'is_active' => 'boolean',
    ];
    }

    public function store(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    public function city(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function createdBy(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\Brackets\CraftablePro\Models\CraftableProUser::class, 'created_by');
    }

    public function items(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Item::class);
    }

    public function supplierTaxTypes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(SupplierTaxType::class);
    }
}
